# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Sonar

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js 13
      uses: actions/setup-node@v1
      with:
        node-version: 13
    - name: Build with npm
      run: |
        npm ci
        npm run build --if-present
        npm test
        
    - name: SonarCloud
      uses: sonarsource/sonarcloud-github-action@master
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
      with:
        args: >
          -Dsonar.organization=mastercard
          -Dsonar.projectName=oauth1-signer-nodejs
          -Dsonar.projectKey=Mastercard_oauth1-signer-nodejs
          -Dsonar.sources=./src
          -Dsonar.tests=./test
          -Dsonar.testExecutionReportPaths=test-results.xml
          -Dsonar.javascript.lcov.reportPaths=.nyc_output/coverage.lcov
          -Dsonar.host.url=https://sonarcloud.io 
          -Dsonar.login=${{ secrets.SONAR_TOKEN }}
